<?xml version="1.0"  encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:java="http://xml.apache.org/xslt/java" exclude-result-prefixes="java">
	<xsl:output method="xml" indent="yes" omit-xml-declaration="no"/>
	<xsl:template match="/">
		<xsl:apply-templates></xsl:apply-templates>
	</xsl:template>
	
	<xsl:template match="DOCUMENT">
<xsl:text disable-output-escaping="yes">
&lt;!DOCTYPE xsl:stylesheet [
   &lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
]&gt;
</xsl:text>
<DOCUMENT  dataTier="{@dataTier}" version="{@version}">
	<index>
		<xsl:for-each select="SUBJECTAREA">
			<xsl:variable name="SA" select="SA_NAME"/>
			<item>
				<type>Subject Area</type>
				<referenceName><xsl:value-of select="SA_NAME"></xsl:value-of></referenceName>
				<subjectArea><xsl:value-of select="SA_NAME"></xsl:value-of></subjectArea>
				<tbCreator/>
				<tbName/>
				<remarks><xsl:value-of select="SA_DESCRIPTION"></xsl:value-of></remarks>
				<parentCreator/>
				<parentName/>
			</item>
			<xsl:for-each select="SCHEMA/TABLES/TABLE">
				<item>
					<type>Table</type>
					<referenceName><xsl:value-of select="NAME"></xsl:value-of></referenceName>
					<subjectArea><xsl:value-of select="$SA"></xsl:value-of></subjectArea>
					<tbCreator><xsl:value-of select="../../SCHEMA_NAME"/></tbCreator>
					<tbName><xsl:value-of select="NAME"/></tbName>
					<remarks><xsl:value-of select="COMMENTS | REMARKS"/></remarks>
					<parentCreator/>
					<parentName/>
				</item>	
				<xsl:for-each select="COLUMNS/COLUMN">
					<item>
						<type>Column</type>
						<referenceName><xsl:value-of select="NAME"></xsl:value-of></referenceName>
						<subjectArea><xsl:value-of select="$SA"></xsl:value-of></subjectArea>
						<tbCreator><xsl:value-of select="../../../../SCHEMA_NAME"/></tbCreator>
						<tbName><xsl:value-of select="../../NAME"/></tbName>
						<remarks><xsl:value-of select="COMMENTS | REMARKS"/></remarks>
						<parentCreator/>
						<parentName/>
					</item>			
				</xsl:for-each>
				<xsl:for-each select="INDICES/INDEX">
					<item>
						<type>Index</type>
						<referenceName><xsl:value-of select="NAME"></xsl:value-of></referenceName>
						<subjectArea><xsl:value-of select="$SA"></xsl:value-of></subjectArea>
						<tbCreator><xsl:value-of select="../../../../SCHEMA_NAME"/></tbCreator>
						<tbName><xsl:value-of select="../../NAME"/></tbName>
						<remarks>
							<xsl:choose>
								<xsl:when test="uniqueRule = 'C' ">
									Unique to enforce the uniqueness of a UNIQUE constraint or hash key columns
								</xsl:when>
								<xsl:when test="uniqueRule = 'D' ">
									Duplicates Allowed
								</xsl:when>
								<xsl:when test="uniqueRule = 'U' ">
									Unique
								</xsl:when>
								<xsl:when test="uniqueRule = 'P' ">
									Primary key index (Unique)
								</xsl:when>
								<xsl:when test="uniqueRule = 'N' ">
									Unique where NOT NULL 
								</xsl:when>	
								<xsl:when test="uniqueRule = 'R' ">
									Unique to enforce the uniqueness of a non-primary parent key
								</xsl:when>	
								<xsl:when test="uniqueRule = 'G' ">
									Unique to enforce the uniqueness of values in a column defined as ROWID GENERATED BY DEFAULT
								</xsl:when>	
								<xsl:when test="uniqueRule = 'X' ">
									Unique to enforce the uniqueness of values in a column that is used to identify or find XML values associated with a specific row
								</xsl:when>	
								<xsl:otherwise>
									<xsl:value-of select="uniqueRule"/> 
								</xsl:otherwise>	
							</xsl:choose>							
						</remarks>
						<parentCreator/>
						<parentName/>
					</item>			
				</xsl:for-each>
				<xsl:for-each select="RELATIONSHIPS/RELATIONSHIP">
					<item>
						<type>Relationship</type>
						<referenceName><xsl:value-of select="RELNAME"/></referenceName>
						<subjectArea><xsl:value-of select="$SA"/></subjectArea>
						<tbCreator><xsl:value-of select="../../../../SCHEMA_NAME"/></tbCreator>
						<tbName><xsl:value-of select="../../NAME"/></tbName>
						<remarks>
							<xsl:value-of select="DELETERULE"/> 
						</remarks>
						<parentCreator><xsl:value-of select="REFTBCREATOR"/></parentCreator>
						<parentName><xsl:value-of select="REFTBNAME"/></parentName>
					</item>			
				</xsl:for-each>	
				<xsl:for-each select="VIEWS/VIEW">
					<item>
						<type>View</type>
						<referenceName><xsl:value-of select="NAME"/></referenceName>
						<subjectArea><xsl:value-of select="$SA"/></subjectArea>
						<tbCreator><xsl:value-of select="SCHEMA | CREATOR"/></tbCreator>
						<tbName><xsl:value-of select="NAME"/></tbName>
						<remarks>
						</remarks>
						<parentCreator><xsl:value-of select="../../../../SCHEMA_NAME"/></parentCreator>
						<parentName><xsl:value-of select="../../NAME"/></parentName>
					</item>			
				</xsl:for-each>															
			</xsl:for-each>
		</xsl:for-each>
	</index>
</DOCUMENT>
	</xsl:template>
</xsl:stylesheet>