<?xml version="1.0"  encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" xmlns:java="http://xml.apache.org/xslt/java" exclude-result-prefixes="java">
	<xsl:output method="html" indent="yes" />
	<xsl:template match="/">
		<xsl:apply-templates></xsl:apply-templates>
	</xsl:template>
	
	<xsl:template match="DOCUMENT">
<html lang="en">
	<head>
	<meta charset="utf-8"></meta>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
	<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
	<meta name="description" content=""></meta>
	<meta name="author" content=""></meta>
	<title>Welcome - The Services Information Warehouse (SIW) Information Catalog (<xsl:value-of select="@dataTier"/> v<xsl:value-of select="@version"/>)</title>
	</head>
	<body>
	<div style="padding-left: .25cm; width: 99%">
		<h1 class="page-header">The Services Information Warehouse (SIW) Information Catalog</h1>
		<p class="dtk-intro">Welcome to the SIW Information Catalog documentation.  You are browsing an overview and database specification for the SIW 
		<strong id="versionId"><xsl:value-of select="@dataTier"/></strong> layer, version <strong id="versionId"><xsl:value-of select="@version"/></strong>. 
		Use the selector to the left to change the data tier and/or the versions.  Then use the popup menu&apos;s to refresh the selection tree.</p>
		<p class="dtk-intro">To find the object you&apos;re interested in, use the tree to the left...or use the quick links below.  </p>
		<div class="dtk-objects">
			<h2>The general information documents of the Services Information Warehouse</h2>
			<div class="dtk-object">
				<div class="dtk-object-image dtk-execSummary"></div>
				<div class="dtk-object-title"><a href="#" onclick="moduleTree.showBasePane('id_executiveSummary', 'executiveSummary','SIW Executive Summary')">Executive Summary</a></div>
				<div class="dtk-object-description">High level mission statement for the SIW.</div>
			</div>
			<div class="dtk-object">
				<div class="dtk-object-image dtk-overview"></div>
				<div class="dtk-object-title"><a href="#" onclick="moduleTree.showBasePane('id_overview', 'overview','SIW Overview')">Overview</a></div>
				<div class="dtk-object-description">What is a data warehouse and what value does it provide?</div>
			</div>
			<div class="dtk-object">
				<div class="dtk-object-image dtk-architecture"></div>
				<div class="dtk-object-title"><a href="#" onclick="moduleTree.showBasePane('id_architecture', 'architecture','SIW Architecture')">Architecture</a></div>
				<div class="dtk-object-description">The SIW architecture defines the solution components and set individual boundaries on the components of the overall solution.</div>
			</div>
			<div class="dtk-object">
				<div class="dtk-object-image dtk-dataFlow"></div>
				<div class="dtk-object-title"><a href="#" onclick="moduleTree.showBasePane('id_dataFlow', '{@dataTier}/{@version}/dataFlow','SIW {@dataTier} v{@version} Data Flow')"><xsl:value-of select="@dataTier"/> v<xsl:value-of select="@version"/> Data Flow</a></div>
				<div class="dtk-object-description">The system context diagram showing the inputs and outputs for the SIW <xsl:value-of select="@dataTier"/> v<xsl:value-of select="@version"/> data tier.</div>
			</div>
			<div class="clear"></div>
			<h2>Subject Areas for SIW <xsl:value-of select="@dataTier"/> v<xsl:value-of select="@version"/></h2>
			<xsl:for-each select="SUBJECTAREA">
            <div class="dtk-object">
              <div class="dtk-object-image dtk-subjectArea"></div>
              <div class="dtk-object-title"><a href="#" onclick="javascript:moduleTree.openById('{SA_NAME}/')"><xsl:value-of select="SA_NAME"/></a></div>
              <div class="dtk-object-description"><xsl:value-of select="SA_DESCRIPTION"/></div>
            </div>
			</xsl:for-each>
		</div>
	</div>
	<div style="display: inline-block;">
		<hr/>
		<p class="dtk-intro"><a href="mailto:ponessa@us.ibm.com">Submit a bug or feature</a> or send note to Steven Ponessa/Sterling Forest/IBM@IBMUS</p>
		
		<p>For further reference and developer documentation, see <a href="https://w3-connections.ibm.com/communities/service/html/communityoverview?communityUuid=cb494052-f712-4214-bcfa-4355eb2f4e40#fullpageWidgetId=W68a6e9d59b58_4665_8fbd_de5280d37749">
		Services IW End User Community - Files</a>.   These documentations contains more detailed, developer-targeted descriptions, with conceptual overviews, 
		and definitions of terms.  This catalog was generated by IBM CIO Application Architecture Information Catalog Compiler on <xsl:value-of select="java:format(java:java.text.SimpleDateFormat.new('yyyy-MM-dd HH:mm:ss.SSS'), java:java.util.Date.new())" />.</p>
	</div> 
	</body>
</html>
	</xsl:template>
	
</xsl:stylesheet>
